### ISSUE TITLE
Please consider adding Acquia to the list of adopters

### ISSUE THREAD

**Issue by anavarre** [theia-ide/theia-website#121]
My colleague @joazvsoares reached out to @akosyakov a few weeks ago about this but we didn't yet have a page up on our website. Now [we do](https://www.acquia.com/products/drupal-cloud/cloud-ide)! We're proud [Theia adopters](https://docs.acquia.com/dev-studio/ide/ui/#) and would be humbled to be added to your list of adopters. We've developed the only optimized Drupal IDE out there and have had great feedback so far. We even have a Theia enthusiast already embracing the product.

Here's our logo in PNG, I hope this works for you.

![acquia_logo](https://user-images.githubusercontent.com/293478/87529314-18fbce80-c68f-11ea-92b1-263505e30d75.png)

**Comment by akosyakov** [comment]
@jankeromnes @nisarhassan12 Could we add?

**Comment by jankeromnes** [comment]
Wow, looks cool! And yes, it would be great to have the Acquia logo on the Theia website.

@nisarhassan12 Could you please add it?

Also, here is an SVG version of the logo: https://theme.zdassets.com/theme_assets/18825/0a64d8b423ca71a12351034a4d5abceb3d7dec22.svg

**Comment by anavarre** [comment]
@nisarhassan12 checking-in to see if you have everything you need, in particular if the above SVG logo works for you? If not, let me please know what you need and I'll make sure to make this happen :wink:

**Comment by nisarhassan12** [comment]
Thanks, @anavarre The SVG works perfectly this is how it looks:

![image](https://user-images.githubusercontent.com/46004116/88272938-e71fe300-ccf2-11ea-9307-7cf25ac8b90a.png)


I'm Sorry for being unresponsive. I have made this https://github.com/theia-ide/theia-website/pull/123 PR to add it to the list.
