### ISSUE TITLE
Get relicensing agreement from tstibbs

### ISSUE THREAD

**Issue by JonasHelming** [theia-ide/theia-website#127]
@tstibbs : I am contacting you via this GH issue, cause there was no mail address provided in your commit.

Dear Theia contributor,

You are receiving this message because the project history shows that you have contributed the following commit(s): 

https://github.com/theia-ide/theia-website/commit/60291e5583614946ea34d82d377dbc5fe1c4ffe1

As you may have heard, Theia has become Eclipse Theia, after joining the Eclipse Foundation, under "Eclipse Cloud Development": https://projects.eclipse.org/projects/ecd.theia. To complete the move, we seek your permission to re-license your contribution on the Theia website above, so they may be kept, as part of the Eclipse Theia project. 

Please answer the questions below, by replying to this email, as soon as possible:

---------

1] Did you agree to contribute the code to the Theia project, 

 

a) to be licensed as open source under the Apache 2.0 license; and

now

 

b) to be licensed as open source under the Eclipse Public License 2.0 [1] with Secondary License Clause of GPL-2.0 WITH Classpath-exception-2.0 [2]?

 

2] Did you [yourself] write the code you contributed to the Theia project?

 

3] Does anyone else have rights to the code you contributed? [For example,

did you have an agreement with an employer giving the employer rights to

all code you wrote during that time?]

 

[1]  https://www.eclipse.org/legal/epl-2.0/

[2]  https://www.eclipse.org/legal/epl-2.0/faq.php#h.w1np1lrpht6k

---------

This is an open and transparent process. You may find the details on the Theia project wiki, here:  https://github.com/theia-ide/theia-website/wiki/Re-licensing-theia-ide-theia-website

 

Thanks,

 

Jonas & the Eclipse Theia team

**Comment by tstibbs** [comment]
> 1] Did you agree to contribute the code to the Theia project,
> a) to be licensed as open source under the Apache 2.0 license; 

Yes

> and now
> b) to be licensed as open source under the Eclipse Public License 2.0 [1] with Secondary License Clause of GPL-2.0 WITH Classpath-exception-2.0 [2]?

Yes

> 2] Did you [yourself] write the code you contributed to the Theia project?

Yes

> 3] Does anyone else have rights to the code you contributed

No
