### ISSUE TITLE
Improve the website's Lighthouse audit scores

### ISSUE THREAD

**Issue by jankeromnes** [theia-ide/theia-website#19]
When you open the website in Chrome's Devtools, there is an "Audits" panel that allows you to quickly test the website's performance and verify common best-practices.

Theia's website already has pretty good scores, but they could be improved, and the "Audits" panel gives interesting suggestions:

<img width="549" alt="screenshot 2019-02-04 at 15 52 45" src="https://user-images.githubusercontent.com/599268/52215810-2820ff00-2895-11e9-96ca-49c36e82a08a.png">

This would probably help with website visibility, bounce rate, etc, or simply make visitors happier and more interested in Theia.

**Comment by jankeromnes** [comment]
I guess the biggest win could come from replacing GIFs with muted auto-playing videos, potentially shaving a whopping 6 seconds from page load times(!)

**Comment by jankeromnes** [comment]
Here is a [full profile](https://thefiletree.com/jan/data/www.theia-ide.org-20190305T204846.json?app=data) I just took, to evaluate any improvements we make over time.

I would like to improve the scores by:
- [ ] Using video formats for animated content to save 8.4s. [Learn more](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/replace-animated-gifs-with-video/).
- [ ] Adding a `<meta name="description">` tag. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/description).
- [ ] Removing the `maximum-scale=1` in `<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">`. [Learn more](https://dequeuniversity.com/rules/axe/2.2/meta-viewport?application=lighthouse).
- [ ] Adding an `alt` attribute to `img.feature__icon.feature__icon--gradient`. [Learn more](https://dequeuniversity.com/rules/axe/2.2/image-alt?application=lighthouse).
- [ ] Fixing or removing the `a.feature__icon-holder` "links".
- [ ] Trying to add `{ passive: true }` to the scroll listeners. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners).
- [ ] Adding a `<meta name="theme-color">` tag. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/address-bar).

This should give https://www.theia-ide.org a better ranking and visibility.

Also FYI, its current Alexa Rank is [657,289](https://www.alexa.com/siteinfo/theia-ide.org). It's gotten better recently, but we can probably still improve it.

**Comment by jankeromnes** [comment]
> Trying to add `{ passive: true }` to the scroll listeners. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners).

This will need some feature detection, as explained [here](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#feature-detection).

Something like this (using [Detect It](https://github.com/rafrex/detect-it)) should work:

```js
  elem.addEventListener('touchstart', fn,
    detectIt.passiveEvents ? {passive:true} : false);
```

**Comment by jankeromnes** [comment]
New baseline (and [profile](https://thefiletree.com/jan/data/www.theia-ide.org-20190306T153332.json?app=data)):

<img width="740" alt="screenshot 2019-03-06 at 15 34 49" src="https://user-images.githubusercontent.com/599268/53888810-ac49dc00-4025-11e9-821f-2b2df75e2c1a.png">

**Comment by svenefftinge** [comment]
Much better with the new website.
<img width="912" alt="Screenshot 2019-08-26 at 08 21 42" src="https://user-images.githubusercontent.com/372735/63669533-8fbf7d00-c7da-11e9-84b5-e0b8d2c1d6a2.png">

**Comment by jankeromnes** [comment]
Whoa, so much win! Many many thanks @nisarhassan12! 💯

It's a significant improvement overall, with just a few tiny regressions of 2% in Performance and 10% in SEO, but I'm confident that they'll be easy / pretty quick to fix. 😄

**Comment by nisarhassan12** [comment]
Thanks! @jankeromnes I will try to improve it :slightly_smiling_face:

**Comment by jankeromnes** [comment]
Really cool! But no urgency though 🙂 the new website is amazing!

**Comment by jankeromnes** [comment]
I was able to improve Accessibility 8%, Best Practices 7% and SEO 1% (and make the website 2.6 MB lighter) in https://github.com/theia-ide/theia-website/pull/46:

<img width="725" alt="Screenshot 2019-08-28 at 10 30 49" src="https://user-images.githubusercontent.com/599268/63839114-ef568d80-c97e-11e9-86fe-736bb7b659d7.png">

**Comment by nisarhassan12** [comment]
Thanks! @jankeromnes
