### ISSUE TITLE
Suggestion for a new website design

### ISSUE THREAD

**Issue by ChristinFrohne** [theia-ide/theia-website#31]
I created a mockup with a new design for the website. Please leave a comment, if you have further suggestions. 

![Home screen](https://user-images.githubusercontent.com/46345125/61874546-f9e9b700-aee8-11e9-952f-a58be54d2ec5.png)

Documentation:
![Documentation](https://user-images.githubusercontent.com/46345125/61874155-fc97dc80-aee7-11e9-9260-7efba0d08bb9.png)

Developer view:
https://xd.adobe.com/spec/8d67cdda-b374-4a22-6578-b05732027502-fb56/screen/f3c8efc7-62cb-4c2b-817a-20174663119d/Home-screen/
[Files.zip](https://github.com/theia-ide/theia-website/files/3431557/Files.zip)

**Comment by nisarhassan12** [comment]
@ChristinFrohne Could you please provide me the SAP logo Svg in the Contributors Section?

**Comment by svenefftinge** [comment]
Thanks 🎉
