### ISSUE TITLE
Add redirect from doc/ to docs/

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia-website#38]
The docs were at doc/ previously. And there are links out there which should be redirected.

**Comment by nisarhassan12** [comment]
Sorry, @svenefftinge I have searched across components, index page, docs page, and all the MDX files and I have not found any link that is still pointing to `/doc` instead of `/docs`. I will try to find once more Would be helpful if you were enlist some of them :slightly_smiling_face:

**Comment by svenefftinge** [comment]
I meant external links in the wild. not within the project.

**Comment by nisarhassan12** [comment]
So should I make that `/doc` again? :slightly_smiling_face:

**Comment by svenefftinge** [comment]
That would not help as the old links have .html at the end.
Ideally we use a redirect plug-in from gatsby and redirect all the old pages.

**Comment by danieltomasku** [comment]
I would like to help with this if possible. You can easily setup redirects with Netilfy using a `netlify.toml` file. Here's some [documentation](https://www.netlify.com/docs/netlify-toml-reference/) on it. It would look something like this in the `netlify.toml` file:
```
redirects = [
    {from = "/doc", to = "/docs", status = 301},
    {from = "/doc/*", to = "/docs/:splat", status = 301"}]
```
This handles the case of `.html` at the end of links as well. The 301 status code tells the browser it is a URL redirection and helps search engines update their results as well.

I can make a pull request for this if you'd like! 🙂

**Comment by nisarhassan12** [comment]
Thanks a lot! @danieltomasku You are welcome to make the PR :slightly_smiling_face:

**Comment by danieltomasku** [comment]
Sounds good @nisarhassan12 ! I think I might need push permissions.

**Comment by nisarhassan12** [comment]
Hey! @danieltomasku You can fork this repo and make the changes and then make a PR from there :slightly_smiling_face:

**Comment by svenefftinge** [comment]
Thank you, it works very well!
