### ISSUE TITLE
[docs] Syntax coloring

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia-website#39]
The code snippets should be syntax colored. See https://github.com/gitpod-io/website on how to do that.

**Comment by nisarhassan12** [comment]
@svenefftinge I tried it the way it was set up on  https://github.com/gitpod-io/website but it does seem to work properly in my case. I have committed the changes to a separate branch. Please have a look at this commit https://github.com/theia-ide/theia-website/commit/afc30f194b72e122bbc18bda2cf435571b7cf17b  whenever you're comfortable and have time :slightly_smiling_face:

**Comment by nisarhassan12** [comment]
Fixed in #104
