### ISSUE TITLE
Suggestions for layout improvements

### ISSUE THREAD

**Issue by ChristinFrohne** [theia-ide/theia-website#40]
Here are some small suggestions:

 - [x] the screenshot should be aligned with the text on both sides
 - [x] the GitHub stars are disappearing depending on the window size
 - [x] the font of the headline as well as the text and the logo is a bit too big
 - [x] `contributors & adopters` should be moved down a bit closer to the brands
 - [x] logos could be a bit smaller and rather have more spacing in between
 - [x] Let's rather use versus instead of `Theia vs. VS Code`
 - [x] in the three boxes the images should have a margin and I'd recommend using a gray box behind the images, just like I suggested in the Mockup
 - [x] the Spectrum logo is too small in comparison to the GitHub and Twitter logo
 - [x] in the mobile view the text should always be displayed above the images. Currently, `integrated terminals` are shown underneath the image

Documentation:

 - [x] screenshot should be aligned with the text
 - [x] smaller arrows to go to the next page
 - [x] can the graphic in the navigation on the left side stay the same while clicking through there?
 - [x] left navigation should be aligned with the shields

**Comment by ChristinFrohne** [comment]
Also, is it possible to give the navigation bar on the documentation site a fixed position? It'd be nice if only the text on the right is moving

**Comment by ChristinFrohne** [comment]
And if you find some time, it'd be nice to add some hover effects for buttons and links

**Comment by nisarhassan12** [comment]
Thanks, @ChristinFrohne Currently! I'm working on other issues. I will look into this one afterward.

**Comment by nisarhassan12** [comment]
@ChristinFrohne I can't align the Screenshot with the text in `docs` and `home` page because it's already aligned! the whitespace and the shadow you're seeing on the sides are part of the image. It would be great if you were to crop the Screenshot and remove them. That way the image would align correctly with the text. And about the shadow I can easily add that with CSS :slightly_smiling_face:

**Comment by ChristinFrohne** [comment]
> @ChristinFrohne I can't align the Screenshot with the text in `docs` and `home` page because it's already aligned! the whitespace and the shadow you're seeing on the sides are part of the image. It would be great if you were to crop the Screenshot and remove them. That way the image would align correctly with the text. And about the shadow I can easily add that with CSS 🙂

Sure, here is the screenshot without shadows :) 

![theia-screenshot-no-shadow](https://user-images.githubusercontent.com/46345125/63749183-32473100-c8ab-11e9-8bbd-c77c1188957d.png)

**Comment by nisarhassan12** [comment]
Thanks! @ChristinFrohne .
Could you please explain what do you mean by this 
![image](https://user-images.githubusercontent.com/46004116/63749727-79dab680-c8c5-11e9-90ac-469a61ce9197.png)

**Comment by ChristinFrohne** [comment]
Of course! I mean that the word "Architecture" should be aligned in its height with the shields. Currently, it's somewhere between the headline "Theia, cloud & desktop IDE" and the shields. 
Is it more clear now? 
Also, what about the search function. Is it possible to implement it? If yes, the search bar should be aligned with it.

**Comment by nisarhassan12** [comment]
> Also, is it possible to give the navigation bar on the documentation site a fixed position? It'd be nice if only the text on the right is moving

Sure! It's possible! I will have a look at it later maybe in a few days.

**Comment by nisarhassan12** [comment]
> Of course! I mean that the word "Architecture" should be aligned in its height with the shields. Currently, it's somewhere between the headline "Theia, cloud & desktop IDE" and the shields.
> Is it more clear now?
> Also, what about the search function. Is it possible to implement it? If yes, the search bar should be aligned with it.

Yes! Thanks!
