### ISSUE TITLE
Website has no favicon

### ISSUE THREAD

**Issue by jankeromnes** [theia-ide/theia-website#47]
I notice that a `favicon.ico` is imported here:

https://github.com/theia-ide/theia-website/blob/b7c568fea922b81efec4dd3529bd681670b0ac47/src/layouts/layout.js#L6

... but it's never used.

Ideally, the website should have two favicons, one 196x196 PNG and one SVG:

```html
<link rel="icon" type="image/png" href="/static/theia-logo-196x196.png" sizes="196x196" />
<link rel="icon" type="image/svg+xml" href="/static/theia-logo.svg" sizes="any" />
```

**Comment by jankeromnes** [comment]
Thanks @nisarhassan12!

Technically, having two favicons (one 196x196 PNG and one SVG) is better, and you can even add a 180x180 apple-touch-icon.png, and another 512x512 PNG for good measure.

You've added a 96x96 PNG. I guess that's good enough for now, but we should probably improve that in the future.

**Comment by nisarhassan12** [comment]
Thanks @jankeromnes :smile:   Actually, I was not able to find Theia logo SVG without text otherwise I would have already added it. Now I have found that will add that in a few minutes.
