### ISSUE TITLE
[seo] canonical URL meta tags don't work properly

### ISSUE THREAD

**Issue by jankeromnes** [theia-ide/theia-website#49]
I've noticed that canonical URL tags are already implemented:

https://github.com/theia-ide/theia-website/blob/d6c03f7e1d0199588dbded8c71d724546a1bf5ec/src/layouts/layout.js#L140-L142

They're even properly set by each page:

https://github.com/theia-ide/theia-website/blob/d6c03f7e1d0199588dbded8c71d724546a1bf5ec/src/pages/index.js#L320

https://github.com/theia-ide/theia-website/blob/ef59c54e02a9203126b71ac28f9c1713923d5783/src/pages/docs.js#L19

And when you load the website, and wait for it to do all the JS things, you can find the right canonical tags in the page:

<img width="1552" alt="Screenshot 2019-08-28 at 08 36 06" src="https://user-images.githubusercontent.com/599268/63831571-2e7ce280-c96f-11e9-90fc-52a36477d5ed.png">

However, it seems that they are not generated server-side, and thus they are not present in the initial page load:

<img width="1552" alt="Screenshot 2019-08-28 at 08 39 26" src="https://user-images.githubusercontent.com/599268/63831648-5ec48100-c96f-11e9-9423-5d9db8dc9c49.png">

This causes the canonical tags to not be detected by bots, i.e. they don't work:

<img width="1552" alt="Screenshot 2019-08-28 at 08 37 49" src="https://user-images.githubusercontent.com/599268/63831670-70a62400-c96f-11e9-89c5-4ff61e38e16b.png">

I suspect that the `<Helmet>` element is not being pre-compiled server-side. Maybe this is because of a missing Gatsby plugin?

It would be great to have the Helmet meta tags working properly to get all the SEO benefits. 🙂

**Comment by nisarhassan12** [comment]
Thanks, @jankeromnes Your Suspicion was correct I was missing the mention of the plugin `gatsby-plugin-react-helmet` in `gatsby-config.js` though it was already installed :slightly_smiling_face: .

**Comment by jankeromnes** [comment]
Indeed, thanks @nisarhassan12! I see that you've added it in 7be22109eb7061c07c2273407bea354ae7b788c2, and now the canonical URLs work fine:

<img width="1364" alt="Screenshot 2019-08-28 at 16 05 39" src="https://user-images.githubusercontent.com/599268/63862990-ca2d4380-c9ad-11e9-96c5-0a70c94cb01a.png">

🎉
