### ISSUE TITLE
Update repository link

### ISSUE THREAD

**Issue by jankeromnes** [theia-ide/theia-website#51]
This repository has the following link next to its decription:

```
http://theia-ide.org
```

Instead, it should be the canonical link:

```
https://www.theia-ide.org/
```

**Comment by nisarhassan12** [comment]
@jankeromnes I also can't change this because I don't have admin access :slightly_smiling_face: .

**Comment by svenefftinge** [comment]
Why should it be www.? I don't think that's very modern...

**Comment by jankeromnes** [comment]
Then maybe HTTPS at least?

I also prefer websites without www. Maybe we make the non-www domain canonical.

**Comment by svenefftinge** [comment]
done
