### ISSUE TITLE
'TextMate' coloring category formatted inconsistently 

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia-website#56]
The `TextMate Coloring` category present in the docs is formatted oddly compared to other categories. The alignment is not consistent:

<div align='left'>

![image](https://user-images.githubusercontent.com/40359487/64609830-c92be700-d39b-11e9-907a-d1380754a37e.png)

</div>

**Comment by nisarhassan12** [comment]
I made it this way because it was specified in issue #31  @akosyakov @JanKoehnlein What do you say Should I remove this indentation for TextMate Coloring?

**Comment by JanKoehnlein** [comment]
As it is it looks strange. But it's a subsection of _Adding Language Support_ so it makes sense. I think we should rather add more documentation, such that we have more on this layer, to make it look less odd.

**Comment by vince-fugnitto** [comment]
> I made it this way because it was specified in issue #31 @akosyakov @JanKoehnlein What do you say Should I remove this indentation for TextMate Coloring?

Ahh I understand the reasoning now. Perhaps subsections can have different styling in general as compared to sections in order to better visualize the differences between the two.

**Comment by nisarhassan12** [comment]
@vince-fugnitto Does this looks ok now?
![image](https://user-images.githubusercontent.com/46004116/65299931-fbeb9180-db8a-11e9-8918-74735786fcc0.png)

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Does this looks ok now?

I think it's good to differentiate the subsections like you did, just not sure about an arrow.
Perhaps a simple bullet point would be more appropriate?

**Comment by nisarhassan12** [comment]
> > @vince-fugnitto Does this looks ok now?
> 
> I think it's good to differentiate the subsections like you did, just not sure about an arrow.
> Perhaps a simple bullet point would be more appropriate?

I agree! i also think a bullet point would be more descriptive and would not alienate the user as an arrow can do. People are not used to of seeing arrow for indicating sublist and so on.
Thanks :smile: 
![image](https://user-images.githubusercontent.com/46004116/65335353-b86e4300-dbdd-11e9-905b-184880cfd832.png)
