### ISSUE TITLE
Coming soon/In construction for empty documentation pages

### ISSUE THREAD

**Issue by epatpol** [theia-ide/theia-website#6]
As mentionned by someone on Gitter, i.e http://www.theia-ide.org/doc/Composing_Applications.html. Or remove it if there's no plans soon to fill it.

**Comment by akosyakov** [comment]
Someone should fill it, a related issue  in Theia: https://github.com/theia-ide/theia/issues/1197

**Comment by akosyakov** [comment]
Will be fixed by https://github.com/theia-ide/theia-website/pull/11
