### ISSUE TITLE
Update website title to be more representative/less confusing

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia-website#62]
**Question**

Currently, we display _Cloud & Desktop IDE_ as the main title for the website. 
Would it not be better (more representative/less confusing) to be more explicit and write 
_Cloud & Desktop IDE **Framework**_?

Theia is not an IDE in itself, it is a framework/platform.
 There is always questions in the community asking if we are a framework or an IDE.

<div align='center'>

<img width="623" alt="Screen Shot 2019-09-20 at 6 04 52 PM" src="https://user-images.githubusercontent.com/40359487/65361455-979ff080-dbd1-11e9-9c96-04a75ded1f85.png">

</div>

**Comment by nisarhassan12** [comment]
> **Question**
> 
> Currently, we display _Cloud & Desktop IDE_ as the main title for the website.
> Would it not be better (more representative/less confusing) to be more explicit and write
> _Cloud & Desktop IDE **Framework**_?
> 
> Theia is not an IDE in itself, it is a framework/platform.
> There is always questions in the community asking if we are a framework or an IDE.
> <img alt="Screen Shot 2019-09-20 at 6 04 52 PM" width="623" src="https://user-images.githubusercontent.com/40359487/65361455-979ff080-dbd1-11e9-9c96-04a75ded1f85.png">

@JanKoehnlein @akosyakov What do you think does it make sense to append the word  **Framework** to the end of the title  :slightly_smiling_face:?

**Comment by vince-fugnitto** [comment]
@marcdumais-work I think adding `Framework` or `Platform` would cause less overall confusion of what Theia actually is?

**Comment by akosyakov** [comment]
@vince-fugnitto true, but it also longer header, maybe `Cloud & Desktop IDEs` we have a definition then with `framework` below

@svenefftinge ?

**Comment by svenefftinge** [comment]
I agree with @vince-fugnitto. It's important to clarify that.
