### ISSUE TITLE
Site does not have a custom 404 page.

### ISSUE THREAD

**Issue by nisarhassan12** [theia-ide/theia-website#78]
@ChristinFrohne Can you please give me a mockup so that i can make one.

**Comment by ChristinFrohne** [comment]
Sure, what about this? 
<img width="963" alt="Bildschirmfoto 2020-01-17 um 14 11 49" src="https://user-images.githubusercontent.com/46345125/72614783-6fcc5980-3933-11ea-8ab3-0e85f5fcb338.png">
[404-error.svg.zip](https://github.com/theia-ide/theia-website/files/4076935/404-error.svg.zip)

**Comment by nisarhassan12** [comment]
Thanks! Looks great!
