### ISSUE TITLE
Composing Applications guide is missing some vital steps

### ISSUE THREAD

**Issue by tstibbs** [theia-ide/theia-website#90]
The guide for [composing applications](https://github.com/theia-ide/theia-website/blob/master/src/docs/Composing_Applications.mdx) shows you how to consume VS code plugins. What it misses is that you need to set an environment variable to tell the running theia where the plugins have been downloaded to. Something like this seems to be sufficient:

    export THEIA_DEFAULT_PLUGINS=local-dir:plugins

Additionally, if one of the plugins you add is a webview plugin, it will fail to pull the contents of the view because it tries to connect to a subdomain. For testing/'quick start' one option is to do something like:

    export THEIA_WEBVIEW_EXTERNAL_ENDPOINT={{hostname}}

I'm happy to submit a PR for these issues, however for the second one particularly I know there are security implications of setting that env like that, so I'm not sure how comfortable we are having advice in the docs that cause a security issue?

**Comment by akosyakov** [comment]
> export THEIA_WEBVIEW_EXTERNAL_ENDPOINT={{hostname}}

We can add some guide for webviews. But doing it like that is not recommended it disables all security of webviews.

**Comment by tstibbs** [comment]
@akosyakov apologies, webviews do work from localhost without that workaround (I was running in a docker container and my setup was complicating things).

I think the first one is still valid though, are you happy to accept a PR to add that in?

**Comment by vince-fugnitto** [comment]
> I think the first one is still valid though, are you happy to accept a PR to add that in?

@tstibbs yes, please go ahead and submit a pull-request to update the documentation and include setting the environment variable :)
