### ISSUE TITLE
Add TORO to the list of adopters

### ISSUE THREAD

**Issue by Hanksha** [theia-ide/theia-website#92]
Hi,

@akosyakov proposed to add us, TORO, to the list of adopters. We're developing a low code development (integration, web API, app) IDE called Martini using Theia. It was originally built with Eclipse RCP for the desktop version and we're porting everything to Theia.

Here is our logo and our website is https://torocloud.com.

[toro-r.svg.zip](https://github.com/theia-ide/theia-website/files/4297370/toro-r.svg.zip)

Let me know if you need anything else.

**Comment by akosyakov** [comment]
@jankeromnes @svenefftinge Could @nisarhassan12 take care of it?

**Comment by vince-fugnitto** [comment]
@JonasHelming I was thinking, would you like **EclipseSource** to be represented as well?
https://theia-ide.org/

**Comment by JonasHelming** [comment]
@vince-fugnitto : Yes, I would like that, thank you for asking!
https://eclipsesource.com

[es-logo.zip](https://github.com/theia-ide/theia-website/files/4298230/es-logo.zip)

Please let me know if you need anything else or if you want me to open a PR..

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto : Yes, I would like that, thank you for asking!

@JonasHelming no problem! I opened the issue #94 to track the request :)
