### ISSUE TITLE
adopters: add 'EclipseSource' to the list of adopters

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia-website#94]
**Description**

We should include **EclipseSource** to the list of adopters from the [main website page](https://theia-ide.org/). <br />Original https://github.com/theia-ide/theia-website/issues/92#issuecomment-595740544

**Additional Info**:
- https://eclipsesource.com
- [es-logo.zip](https://github.com/theia-ide/theia-website/files/4298230/es-logo.zip)

cc @nisarhassan12 if possible, could you take of it like you have done already for TORO?
cc @JonasHelming

**Comment by akosyakov** [comment]
An adopter is someone who build a solution based on Theia. TORO is rewriting their current solutions (https://www.torocloud.com/) with Theia, that's a reason to be mentioned.

For EclipseSource to be eligible they should share own solutions.

**Comment by akosyakov** [comment]
cc @svenefftinge

**Comment by vince-fugnitto** [comment]
> For EclipseSource to be eligible they should share own solutions.

@akosyakov the page itself lists _'Contributors & Adopters'_ and it can be argued that _EclipseSource_ is in fact an important contributor since:
- they actively contribute directly to the main framework
- they have multiple articles regarding the framework
- they have worked in modeling: [eclipse-glsp](https://github.com/eclipse-glsp/glsp)

What is (or should be) the main criteria before accepting a new company to the page?

**Comment by akosyakov** [comment]
> they actively contribute directly to the main framework

I don't know any significant contributions.

> they have multiple articles regarding the framework

We rather should have own articles under this website and share own knowledge than point and rely on external content. In addition, in these articles I'm not able to see a single reference, mention or credits to TypeFox or Ericsson who actually doing hard job to build Theia and its community. If they contributed such content to the website as a reference documentation agnostic to any vendors we could talk about contributions, as RedHat for instance did for the plugin system. Otherwise it is an attempt to hijack attention from theia-ide.org.

> they have worked in modeling: eclipse-glsp

If it would be fine without bitterness of 2 points above.

> What is (or should be) the main criteria before accepting a new company to the page?

Not trying to hijack a community would be a good start.

**Comment by JonasHelming** [comment]
We adopt Eclipse Theia for: 

- the implementation of [cloud-based Ecore tools](https://github.com/eclipsesource/ecore-glsp) as part of the [emf.cloud](https://www.eclipse.org/emfcloud/) project
- the implementation of the [coffee editor](https://github.com/eclipsesource/coffee-editor)
- the integration of the emf.cloud [model server](https://github.com/eclipse-emfcloud/emfcloud-modelserver-theia)
- the integration of the [GSLP diagram client](https://github.com/eclipse-glsp/glsp-theia-integration)
- the integration of the [JSON Forms tree editor](https://github.com/eclipsesource/theia-tree-editor)

Further we adopt Theia in several non-public customer projects..

**Comment by marcdumais-work** [comment]
IMHO these look like valuable contributions, that benefit the greater Theia ecosystem, enabling building things with Theia that were not possible or not so easy before. 

To me this is arguably more valuable than being a "pure adopter" - e.g. a company that has a closed-source Theia product but contributes-back little or nothing to the community. If the adopters category does not fit, maybe we need a new category?

**Comment by akosyakov** [comment]
@nisarhassan12 Could you add EclipseSource as an adopter please?

**Comment by nisarhassan12** [comment]
I have made a PR for this.
