### ISSUE TITLE
Do not advertise the Phosphor layout

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia-website#97]
We do not have to keep it as a secret, the source is open for everyone, but perhaps we should not advertise the PhosphorJS-based layout on the main Theia webpage as the project is archived.

From [here](https://news.ycombinator.com/item?id=22740470):
> On https://theia-ide.org/ it says the shell is based on PhosphorJS. When I follow the link to the repo, it says it's archived. Have they vendored it yet? https://github.com/phosphorjs/phosphor

**Comment by akosyakov** [comment]
We will merge PhosphorJS and make our own widget library in `@theia/core`. Flexible layout can rephrased without PhorsphorJS.

cc @jankeromnes @svenefftinge
